### ISSUE TITLE
Information on AMM and Clawback collaboration

### ISSUE THREAD

**Issue by tequdev** [XRPLF/XRPL-Standards#141]
It is not clearly stated that AMM pools cannot be created with tokens that have Clawback enabled.

**Comment by mvadari** [comment]
It's listed here: https://github.com/XRPLF/XRPL-Standards/tree/master/XLS-0039d-clawback#7-compatibility-with-automated-market-maker-xls-30

**Comment by develoQ** [comment]
This statement gives the perception that it is possible to create an AMM pool with Clawbackable tokens, but it is not possible to Clawback from the AMM pool.

A statement regarding AMMCreate transactions is needed.

**Comment by kennyzlei** [comment]
Thanks for catching this!  We can update the Clawback spec to explicitly state this.  I believe this Clawback spec was derived before the AMMCreate behavior was fully finalized, and now we can update the spec to define the behavior clearer

**Comment by mDuo13** [comment]
https://github.com/XRPLF/xrpl-dev-portal/pull/2245 fixes this on the dev portal
