### ISSUE TITLE
Message signing

### ISSUE THREAD

**Issue by paluh** [XRPLF/XRPL-Standards#253]
Please excuse my basic question - I’m new to XRP. Could you please tell me if there is currently a standard or any plans to establish one for message signing?

**Comment by mvadari** [comment]
Message signing pre-dates the Standards process. 

https://xrpl.org/docs/concepts/accounts/cryptographic-keys

**Comment by paluh** [comment]
Thank you!

I should probably be more precise. I was asking specifically about arbitrary message signing—something along the lines of [EIP-191](https://eips.ethereum.org/EIPS/eip-191#specification, [BIP-0322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki#test-vectors) or [CIP-0008](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0008).

**Comment by mvadari** [comment]
There is no standard. Most libraries support arbitrary message signing, though I'm not sure if any wallets support it.

**Comment by paluh** [comment]
Thanks a lot! I'm closing this thread for now as it is not really a proposal for that standard.
