### ISSUE TITLE
Todo: action to reject new folder without TOML update

### ISSUE THREAD

**Issue by WietseWind** [XRPLF/XRPL-Standards#29]
- [ ] Configure an action that rejects a commit containing a new folder without an update to the `standards.toml` file.

**Comment by Tomyleexrp** [comment]
standards.toml

**Comment by mvadari** [comment]
@WietseWind is this still needed with the current procedures?

**Comment by WietseWind** [comment]
@mvadari Nope, nice catch, can close :)
